### ISSUE TITLE
throttle should be canceled on destroy

### ISSUE THREAD

**Issue by stefanpenner** [trentmwillis/ember-singularity#11]
https://github.com/trentmwillis/ember-singularity/blob/master/addon/services/unified-event-handler.js#L202-L204

**Comment by trentmwillis** [comment]
Discussed offline, this should be fine. Throttle cleans itself up since it either executes immediately or no-ops. The timer aspect of it will clean itself up in backburner land (verified via profiling and looking at [backburner source code](https://github.com/BackburnerJS/backburner.js/blob/b3ea24aa31ff684faccebb782dfadec9090acf2f/lib/index.ts#L469-L471)).
